### ISSUE TITLE
Sls deploy issue

### ISSUE THREAD

**Issue by SmartiAppsTeam** [pgrzesik/serverless-fastapi#1]
When I clone this repo and tried to deploy, I got the  following error

Running "serverless" from node_modules

Deploying aws-python-fastapi to stage dev (us-east-1)

× Stack aws-python-fastapi-dev failed to deploy (73s)
Environment: win32, node 18.16.1, framework 3.38.0 (local) 3.35.2v (global), plugin 7.2.3, SDK 4.5.1
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
UPDATE_FAILED: ApiLambdaFunction (AWS::Lambda::Function)
Resource handler returned message: "Lambda function aws-python-fastapi-dev-api could not be found" (RequestToken: fc875e9c-7949-5c0f-db4a-b0f1f1590a7e, HandlerErrorCode: NotFound)

View the full error: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A566177704644%3Astack%2Faws-python-fastapi-dev%2Fed8e0b20-68e6-11ee-a234-0a8040ddf13b

**Comment by pgrzesik** [comment]
Hello, did you do any changes to the template prior to deploying? Is this the first time deploy or not?

**Comment by SmartiAppsTeam** [comment]
I have fixed deployment issue. This is because of failed cloud formation and s3 bucket. I had deleted it. deployed it again. Now it is working.

**Comment by pgrzesik** [comment]
Thanks a lot for the update @SmartiAppsTeam 🙇
